# github.com/go-task/task

version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  vevn-init:
    desc: Initialize Virtual Environment
    cmds:
      - conda create -n play36 python=3.6
  
  venv:
    desc: use $(task venv). Shows venv enter command
    cmds:
      - echo conda activate play36
    silent: yes
  
  venv-update:
    desc: Update venv deps (pip and conda requirements)
    cmds:
      - pip install opencv-python